name = "littlecathouse"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.txt", "**/*.xml"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.jpg", "**/*.png"]
fallthrough = true
